---
- include_tasks: asserts.yml

  #- include_tasks: ubuntu.yml
  #  when: ansible_distribution == "Ubuntu"
  #- include_tasks: arch.yml
  #  when: ansible_distribution == "Archlinux"
- include_tasks: interface_process.yml
  loop: "{{ nr_interfaces | dict2items }}"
  loop_control:
    loop_var: _i
